version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - checkout
      - run:
          name: Initial Environement Setup
          command: |
            apt-get install gcc
            apt-get install cmake
            echo 'Initial Environement Setup'